### ISSUE TITLE
Warnings on startup

### ISSUE THREAD

**Issue by lukehutch** [appsup-dart/x509#24] opened 2023-08-22 07:02 UTC
I get the following warnings on startup, after upgrading to the latest version of x509:

```console
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/x509_base.dart:176:59: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
                (sequence.elements[2] as ASN1OctetString).contentBytes()!),
                                                          ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/x509_base.dart:195:62: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
        algorithm, (sequence.elements[1] as ASN1OctetString).contentBytes()!);
                                                             ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/certificate.dart:137:19: Warning: Operand of null-aware operation '!' has type 'BigInt' which excludes null.
 - 'BigInt' is from 'dart:core'.
      version = e.valueAsBigInteger!.toInt() + 1;
                  ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/certificate.dart:154:32: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
            ex = (ASN1Parser(o.contentBytes()!).nextObject() as ASN1Sequence)
                               ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/certificate.dart:164:52: Warning: Operand of null-aware operation '!' has type 'BigInt' which excludes null.
 - 'BigInt' is from 'dart:core'.
        serialNumber: (elements[0] as ASN1Integer).valueAsBigInteger!.toInt(),
                                                   ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/extension.dart:47:54: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
            ASN1Parser(sequence.elements[octetIndex].contentBytes()!)
                                                     ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/extension.dart:355:16: Warning: Operand of null-aware operation '!' has type 'bool' which excludes null.
        cA = o.booleanValue!;
               ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/util.dart:39:50: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
  var privateKey = toBigInt(sequence.elements[1].contentBytes()!);
                                                 ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/util.dart:41:32: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
  var l = sequence.elements[1].contentBytes()!.length;
                               ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/util.dart:55:45: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
    var e = ASN1Parser(sequence.elements[i].contentBytes()!).nextObject()
                                            ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/util.dart:101:55: Warning: Operand of null-aware operation '!' has type 'BigInt' which excludes null.
 - 'BigInt' is from 'dart:core'.
  var modulus = (sequence.elements[0] as ASN1Integer).valueAsBigInteger!;
                                                      ^
../../../.pub-cache/hosted/pub.dev/x509-0.2.3/lib/src/util.dart:102:56: Warning: Operand of null-aware operation '!' has type 'BigInt' which excludes null.
 - 'BigInt' is from 'dart:core'.
  var exponent = (sequence.elements[1] as ASN1Integer).valueAsBigInteger!;
                                                       ^
```

**Comment by kmcgill88** [comment] 2023-08-23 14:55
Same here.

x509 version 0.2.3
Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_x64"

**Comment by faithoflifedev** [comment] 2023-09-05 13:29
@lukehutch , @kmcgill88 , I'm seeing the same problem, have you found a work-around?

`Dart SDK version: 3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "macos_arm64"`

**Comment by kmcgill88** [comment] 2023-09-05 13:51
No, for now, I've just ignored the warning @faithoflifedev  🫤

**Comment by faithoflifedev** [comment] 2023-09-05 14:19
@kmcgill88 , I just submitted a PR - https://github.com/appsup-dart/x509/pull/25 - that removes the warning.

**Comment by faithoflifedev** [comment] 2023-09-05 14:42
@kmcgill88, I also added
```
dependency_overrides:
  x509:
    git: https://github.com/faithoflifedev/x509.git
```

to my project to remove the warnings, until the x509 package is updated and republished.

**Comment by eximius313** [comment] 2023-10-12 13:37
The issue is still there.
What are the reasons for not merging [this PR](https://github.com/appsup-dart/x509/pull/25)?

**Comment by rbellens** [comment] 2023-10-13 09:55
the pr is now merged and released.

**Closed by rbellens** 2023-10-13 09:55 UTC

**Comment by eximius313** [comment] 2023-10-13 13:09
Awesome, thanks!

**Comment by lukehutch** [comment] 2023-10-15 05:37
@eximius313 you missed one:

```
../../../.pub-cache/hosted/pub.dev/x509-0.2.4/lib/src/extension.dart:45:48: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
      ASN1Parser(sequence.elements[octetIndex].contentBytes()!).nextObject(),
```

**Comment by lukehutch** [comment] 2023-10-15 05:37
@rbellens you missed one:

```
../../../.pub-cache/hosted/pub.dev/x509-0.2.4/lib/src/extension.dart:45:48: Warning: Operand of null-aware operation '!' has type 'Uint8List' which excludes null.
 - 'Uint8List' is from 'dart:typed_data'.
      ASN1Parser(sequence.elements[octetIndex].contentBytes()!).nextObject(),
```

**Comment by kevan-mtl** [comment] 2023-11-11 07:11
yep same issue for me @lukehutch !
